# Validation Policy for ObjectBox Schema Changes
# pass       - Automatic approval, no intervention needed.
# approval   - Requires a corresponding entry in audit.yaml.
# retirement - Requires the entity to be present in the 'retiredEntityUids' list.

validation_policy:
  ENTITY_ADDED: pass
  PROPERTY_ADDED: pass
  ENTITY_RENAMED: pass
  PROPERTY_RENAMED: pass
  ENTITY_UID_CHANGED: approval
  PROPERTY_UID_CHANGED: approval
  RELATIONSHIP_CHANGED: approval
  PROPERTY_DELETED: approval
  ENTITY_DELETED: retirement
  PROPERTY_TYPE_CHANGED: approval
  PROPERTY_FLAGS_CHANGED: approval
