name: audio_diaries_flutter
description: Audio Diaries Flutter is a mobile application that allows users to record audio diaries and store them locally and in a cloud database. The application is built using Flutter and Dart, and uses Firebase for cloud storage.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.10.0+110

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  app_settings: ^7.0.0

  table_calendar: ^3.2.0
  #Adaptive font
  flutter_screenutil: ^5.9.3

  #Formating
  intl: ^0.20.2

  #firebase
  firebase_core: ^4.8.0
  firebase_crashlytics: ^5.2.1

  permission_handler: ^12.0.1

  #Audio recording & playback
  flutter_sound: ^9.30.0
  audio_session: ^0.2.3
  audioplayers: ^6.6.0

  #Video Playback
  video_player: ^2.11.1
  video_compress: ^3.1.4

  #Camera
  camera: ^0.12.0+1

  #Location
  location: ^8.0.1

  #internal storage
  path_provider: ^2.1.5

  #Http
  http: ^1.6.0

  #path manipulation
  path: ^1.9.1

  #state management
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  #mock tail
  mocktail: ^1.0.5

  #Data
  shared_preferences: ^2.5.5

  #Database
  objectbox: ^5.3.1
  objectbox_flutter_libs: any

  #Animations
  rive: ^0.14.6
  lottie: ^3.3.3

  # amplify_analytics_pinpoint: ^2.6.0
  firebase_messaging: ^16.2.1
  flutter_local_notifications: ^21.0.0

  #Notification
  awesome_notifications: ^0.11.0

  #URL Launcher
  url_launcher: ^6.3.2

  #Web
  webview_flutter: ^4.13.1

  #Pendo
  pendo_sdk: ^3.13.1

  #Splash
  flutter_native_splash: ^2.4.7

  #Misc
  dotted_border: ^3.1.0
  flutter_secure_storage: ^10.2.0
  wakelock_plus: ^1.6.0
  firebase_analytics: ^12.4.0
  package_info_plus: ^10.1.0
  flutter_keyboard_visibility: ^6.0.0
  alarm: ^5.2.1
  gradient_borders: ^1.0.2
  popover: ^0.4.0
  mockito: ^5.6.4
  bloc_test: ^10.0.0
  # disable_battery_optimization: ^1.1.1
  internet_connection_checker_plus: ^3.0.0
  flutter_dotenv: ^6.0.1
  device_info_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  #Database
  build_runner: ^2.15.0
  objectbox_generator: any

  #Icon
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

#Icon Configuration
flutter_launcher_icons:
  image_path: "assets/images/logo_white.png"
  ios: true
  android: true
  min_sdk_android: 24

#Splash Configuration
flutter_native_splash:
  color: "#5B89FF"
  color_dark: "#5B89FF"
  image: "assets/images/logo_white.png"
  android: true
  ios: true
  web: false

  #Device info
  package_info_plus: ^5.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    - assets/images/fops/
    - assets/animations/
    - assets/animations/onboarding/
    - assets/animations/recording/
    - assets/protocol.json
    - assets/onboarding.json
    - assets/fops.json
    - assets/audio/
    - assets/video/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
