import 'package:audio_diaries_flutter/screens/diary/data/option.dart';
import 'package:flutter/material.dart';

import '../../screens/diary/data/diary.dart';
import '../../screens/diary/data/prompt.dart';
import '../../screens/diary/data/tag.dart';
import 'statuses.dart';
import 'types.dart';

List<Diary> exampleDiaries = [
  Diary(
      id: 0,
      prompts: fakePrompts,
      tags: fakeTags,
      status: DiaryStatus.idle,
      due: DateTime.now()),
  Diary(
      id: 1,
      prompts: fakePrompts,
      tags: fakeTags,
      status: DiaryStatus.ongoing,
      due: DateTime.now()),
  Diary(
      id: 2,
      prompts: fakePrompts,
      tags: fakeTags,
      status: DiaryStatus.submitted,
      due: DateTime.now()),
  Diary(
      id: 3,
      prompts: fakePrompts,
      tags: fakeTags,
      status: DiaryStatus.complete,
      due: DateTime.now()),
  Diary(
      id: 4,
      prompts: fakePrompts,
      tags: fakeTags,
      status: DiaryStatus.ongoing,
      due: DateTime.now()),
];

final List<Prompt> fakePrompts = [
  Prompt(
    id: 0,
    question: "How was your day?",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 1,
    question: "How did you overcome an embarrassing moment today",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 2,
    question: "How was your day?",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 3,
    question: "How did you overcome an embarrassing moment today",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 4,
    question: "How was your day?",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 5,
    question: "How did you overcome an embarrassing moment today",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 6,
    question: "How was your day?",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 7,
    question: "How did you overcome an embarrassing moment today",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 8,
    question: "How was your day?",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 9,
    question: "How did you overcome an embarrassing moment today",
    responseType: ResponseType.recording,
  ),
];

final List<Prompt> newPrompts = [
  Prompt(
      id: 0,
      question: "How do yo FEEL PHYSICALLY right now?",
      responseType: ResponseType.slider),
  Prompt(
      id: 1,
      question:
          "How do yo FEEL EMOTIONALLY right now? Please use the slider to rate how PLEASANT or UNPLEASANT you feel emotionally:",
      responseType: ResponseType.slider),
  Prompt(
      id: 2,
      question:
          "Please use the slider to rate the INTENSITY of the overall emotion you are experiencing right now",
      responseType: ResponseType.slider),
  Prompt(
      id: 3,
      question: "I felt lonely today.",
      responseType: ResponseType.slider),
  Prompt(
      id: 4,
      question: "I felt left out today.",
      responseType: ResponseType.slider),
  Prompt(
      id: 5,
      question: "How much social interaction did you have today?",
      responseType: ResponseType.slider),
  Prompt(
      id: 6,
      question: "I felt understood/cared for by others today.",
      responseType: ResponseType.slider),
  Prompt(
      id: 7,
      question: "I felt stressed today.",
      responseType: ResponseType.slider),
  Prompt(
      id: 8,
      question:
          "Which of the following best describes where you are physically right now? Check all that apply.",
      responseType: ResponseType.multiple),
  Prompt(
      id: 9,
      question: "How many people are around you right now?",
      responseType: ResponseType.radio),
  Prompt(
      id: 10,
      question:
          "How many drinks of alcohol have you had in the last 24 hours? A drink is 12 ounces of beer, 5 ounces of wine, or 1.5 ounces of distilled spitits.",
      responseType: ResponseType.slider),
  Prompt(
    id: 11,
    question: "How was your day?",
    responseType: ResponseType.recording,
  ),
  Prompt(
    id: 12,
    question: "How did you overcome an embarrassing moment today",
    responseType: ResponseType.recording,
  ),
];

final List<Option> multipleOptions = [
  Option(id: 0, option: "At home or in my dorm room"),
  Option(id: 1, option: "In someone else's home or dorm room"),
  Option(id: 2, option: "In a car, bus, or other form of transportation"),
  Option(id: 3, option: "Outside"),
  Option(id: 4, option: "In a public place(eg., library, restaurant airport)"),
];

final List<Option> radioOptions = [
  Option(id: 0, option: "0"),
  Option(id: 1, option: "1"),
  Option(id: 2, option: "2"),
  Option(id: 3, option: "3"),
  Option(id: 4, option: "4 or more"),
];

List<Tag> fakeTags = const [
  Tag(text: "60 seconds", type: TagType.time),
  Tag(text: "Multiple questions", type: TagType.questions),
];

const TimeOfDay fixedTime = TimeOfDay(hour: 9, minute: 0);

final List<String> studyCodes = [
  "X8R3Z9",
  "P2F7G6",
  "Q9S5T2",
  "E6D1C4",
  "M7N0B8",
  "H4J6K5",
  "V5W8L3",
  "A3E2R1",
  "T0U9F7",
  "Y1I4O2",
  "B8Q3X6",
  "L2Z7P9",
  "G9M5S2",
  "C6K1D4",
  "N7H0J8",
  "O4V6L5",
  "W5A8E3",
  "F3T2U1",
  "R0Y9I7",
  "X1B4Q6",
  "P8N2Z7",
  "Q5E9M3",
  "H2C6K5",
  "M9L0J8",
  "S6V4W3",
  "B1R3X6",
  "T7G2F9",
  "O4U1Y2",
  "I8D7C5",
  "K5F2T1",
  "J2W9A0",
  "V6Z8P3",
  "E3B4Q7",
  "N0M6H5",
  "L7K1D9",
  "C4S2T8",
  "X1R9I0",
  "P8U6Y2",
  "Q5G3F7",
  "H2N1B6",
  "M9W8L4",
  "S6E5C3",
  "B3K7J0",
  "T0Z9A8",
  "O7Q6X4",
  "I4M2H1",
  "F1T8U5",
  "R8D0Y3",
  "C5B4P6",
  "V2G9Z1",
  "N9K7S3",
  "L6H2C8",
  "W3J1V0",
  "E0N5M4",
  "Y7W6A9",
  "K4Z3P8",
  "J1R2X0",
  "U8T9F6",
  "G5I7O4",
  "X2E4B1",
  "P9Q7Z5",
  "Q6U3L0",
  "H3M2S9",
  "T0K9D8",
  "O7J5C1",
  "I4W8V6",
  "F1A0G3",
  "R8Z6P2",
  "C5X4N9",
  "V2B1T7",
  "N9R7H5",
  "L6U2F8",
  "W3M1Y0",
  "E0K5J4",
  "Y7D3C9",
  "K4G9Q6",
  "J1N8Z2",
  "U8L7X0",
  "G5V6W4",
  "X2S1P3",
  "P9I0O7",
  "Q6F5B2",
  "H3T2U8",
  "T0R9E6",
  "O7Y4A1",
  "I4Q1C8",
  "F1X0N5",
  "R8M7K3",
  "C5J6H9",
  "V2W5D4",
  "N9G4V0",
  "L6U3Z8",
  "W3N2P1",
  "E0L9S7",
  "Y7K8B6",
  "K4F7T2",
  "J1R6U0",
  "U8O5I3",
  "G5D2Q9",
  "X2C1E8",
  "P9Z0M6",
  "Q6P5H4",
  "H3W4J2",
  "T0V9F1",
  "O7B6N8",
  "I4K3T7",
  "F1Z2A0",
  "R8Q1X9",
  "C5U0O6",
  "V2I9G7",
  "N9E8Y5",
  "L6M7C4",
  "W3H6U2",
  "E0T5W1",
  "Y7R4P0",
  "K4D3B9",
  "J1A2N6",
  "U8X1L5",
  "G5K0F8",
  "X2V9S7",
  "P9N8J6",
  "Q6L7Y5",
  "H3U6T4",
  "T0M5K3",
  "O7H4Z2",
  "I4E3X1",
  "F1B2Q0",
  "R8W9O9",
  "C5P8I7",
  "V2F7G6",
  "N9T6U5",
  "L6O5N4",
  "W3M4L3",
  "E0K3J2",
  "Y7H2D1",
  "K4G1C0",
  "J1V9B9",
  "U8Q8Z7",
  "G5N7P6",
  "X2M6S5",
  "P9J5H4",
  "Q6U4T3",
  "H3G3R2",
  "T0E2Q1",
  "O7B1P0",
  "I4Y9N9",
  "F1X8L8",
  "R8W7K6",
  "C5T6I5",
  "V2O5G4",
];
