// Mocks generated by Mockito 5.4.6 from annotations
// in audio_diaries_flutter/test/services/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i10;

import 'package:awesome_notifications/awesome_notifications.dart' as _i2;
import 'package:awesome_notifications/src/enumerators/notification_life_cycle.dart'
    as _i9;
import 'package:awesome_notifications/src/enumerators/notification_permission.dart'
    as _i4;
import 'package:awesome_notifications/src/models/notification_button.dart'
    as _i7;
import 'package:awesome_notifications/src/models/notification_channel.dart'
    as _i13;
import 'package:awesome_notifications/src/models/notification_channel_group.dart'
    as _i14;
import 'package:awesome_notifications/src/models/notification_content.dart'
    as _i5;
import 'package:awesome_notifications/src/models/notification_localization.dart'
    as _i8;
import 'package:awesome_notifications/src/models/notification_model.dart'
    as _i15;
import 'package:awesome_notifications/src/models/notification_schedule.dart'
    as _i6;
import 'package:awesome_notifications/src/models/received_models/received_action.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AwesomeNotifications].
///
/// See the documentation for Mockito's code generation for more information.
class MockAwesomeNotifications extends _i1.Mock
    implements _i2.AwesomeNotifications {
  MockAwesomeNotifications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cancel(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllSchedules() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllSchedules,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotificationsByChannelKey(String? channelKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelNotificationsByChannelKey,
          [channelKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotificationsByGroupKey(String? groupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelNotificationsByGroupKey,
          [groupKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelSchedule(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelSchedule,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelSchedulesByChannelKey(String? channelKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSchedulesByChannelKey,
          [channelKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelSchedulesByGroupKey(String? groupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSchedulesByGroupKey,
          [groupKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.NotificationPermission>> checkPermissionList({
    String? channelKey,
    List<_i4.NotificationPermission>? permissions = const [
      _i4.NotificationPermission.Badge,
      _i4.NotificationPermission.Alert,
      _i4.NotificationPermission.Sound,
      _i4.NotificationPermission.Vibration,
      _i4.NotificationPermission.Light,
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissionList,
          [],
          {
            #channelKey: channelKey,
            #permissions: permissions,
          },
        ),
        returnValue: _i3.Future<List<_i4.NotificationPermission>>.value(
            <_i4.NotificationPermission>[]),
      ) as _i3.Future<List<_i4.NotificationPermission>>);

  @override
  _i3.Future<bool> createNotification({
    required _i5.NotificationContent? content,
    _i6.NotificationSchedule? schedule,
    List<_i7.NotificationActionButton>? actionButtons,
    Map<String, _i8.NotificationLocalization>? localizations,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotification,
          [],
          {
            #content: content,
            #schedule: schedule,
            #actionButtons: actionButtons,
            #localizations: localizations,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> createNotificationFromJsonData(
          Map<String, dynamic>? mapData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotificationFromJsonData,
          [mapData],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> decrementGlobalBadgeCounter() => (super.noSuchMethod(
        Invocation.method(
          #decrementGlobalBadgeCounter,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> dismiss(int? id) => (super.noSuchMethod(
        Invocation.method(
          #dismiss,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dismissAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #dismissAllNotifications,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dismissNotificationsByChannelKey(String? channelKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #dismissNotificationsByChannelKey,
          [channelKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dismissNotificationsByGroupKey(String? groupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #dismissNotificationsByGroupKey,
          [groupKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.NotificationLifeCycle> getAppLifeCycle() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppLifeCycle,
          [],
        ),
        returnValue: _i3.Future<_i9.NotificationLifeCycle>.value(
            _i9.NotificationLifeCycle.Foreground),
      ) as _i3.Future<_i9.NotificationLifeCycle>);

  @override
  _i3.Future<_i10.Uint8List?> getDrawableData(String? drawablePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDrawableData,
          [drawablePath],
        ),
        returnValue: _i3.Future<_i10.Uint8List?>.value(),
      ) as _i3.Future<_i10.Uint8List?>);

  @override
  _i3.Future<_i11.ReceivedAction?> getInitialNotificationAction(
          {bool? removeFromActionEvents = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInitialNotificationAction,
          [],
          {#removeFromActionEvents: removeFromActionEvents},
        ),
        returnValue: _i3.Future<_i11.ReceivedAction?>.value(),
      ) as _i3.Future<_i11.ReceivedAction?>);

  @override
  _i3.Future<int> getGlobalBadgeCounter() => (super.noSuchMethod(
        Invocation.method(
          #getGlobalBadgeCounter,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getLocalTimeZoneIdentifier() => (super.noSuchMethod(
        Invocation.method(
          #getLocalTimeZoneIdentifier,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalTimeZoneIdentifier,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<DateTime?> getNextDate(
    _i6.NotificationSchedule? schedule, {
    DateTime? fixedDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextDate,
          [schedule],
          {#fixedDate: fixedDate},
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<String> getUtcTimeZoneIdentifier() => (super.noSuchMethod(
        Invocation.method(
          #getUtcTimeZoneIdentifier,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getUtcTimeZoneIdentifier,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<int> incrementGlobalBadgeCounter() => (super.noSuchMethod(
        Invocation.method(
          #incrementGlobalBadgeCounter,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> initialize(
    String? defaultIcon,
    List<_i13.NotificationChannel>? channels, {
    List<_i14.NotificationChannelGroup>? channelGroups,
    bool? debug = false,
    String? languageCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            defaultIcon,
            channels,
          ],
          {
            #channelGroups: channelGroups,
            #debug: debug,
            #languageCode: languageCode,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isNotificationAllowed() => (super.noSuchMethod(
        Invocation.method(
          #isNotificationAllowed,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i15.NotificationModel>> listScheduledNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #listScheduledNotifications,
          [],
        ),
        returnValue: _i3.Future<List<_i15.NotificationModel>>.value(
            <_i15.NotificationModel>[]),
      ) as _i3.Future<List<_i15.NotificationModel>>);

  @override
  _i3.Future<bool> removeChannel(String? channelKey) => (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channelKey],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestPermissionToSendNotifications({
    String? channelKey,
    List<_i4.NotificationPermission>? permissions = const [
      _i4.NotificationPermission.Alert,
      _i4.NotificationPermission.Sound,
      _i4.NotificationPermission.Badge,
      _i4.NotificationPermission.Vibration,
      _i4.NotificationPermission.Light,
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermissionToSendNotifications,
          [],
          {
            #channelKey: channelKey,
            #permissions: permissions,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> resetGlobalBadge() => (super.noSuchMethod(
        Invocation.method(
          #resetGlobalBadge,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setChannel(
    _i13.NotificationChannel? notificationChannel, {
    bool? forceUpdate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setChannel,
          [notificationChannel],
          {#forceUpdate: forceUpdate},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setGlobalBadgeCounter(int? amount) => (super.noSuchMethod(
        Invocation.method(
          #setGlobalBadgeCounter,
          [amount],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> setListeners({
    required _i2.ActionHandler? onActionReceivedMethod,
    _i2.NotificationHandler? onNotificationCreatedMethod,
    _i2.NotificationHandler? onNotificationDisplayedMethod,
    _i2.ActionHandler? onDismissActionReceivedMethod,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setListeners,
          [],
          {
            #onActionReceivedMethod: onActionReceivedMethod,
            #onNotificationCreatedMethod: onNotificationCreatedMethod,
            #onNotificationDisplayedMethod: onNotificationDisplayedMethod,
            #onDismissActionReceivedMethod: onDismissActionReceivedMethod,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.NotificationPermission>> shouldShowRationaleToRequest({
    String? channelKey,
    List<_i4.NotificationPermission>? permissions = const [
      _i4.NotificationPermission.Badge,
      _i4.NotificationPermission.Alert,
      _i4.NotificationPermission.Sound,
      _i4.NotificationPermission.Vibration,
      _i4.NotificationPermission.Light,
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldShowRationaleToRequest,
          [],
          {
            #channelKey: channelKey,
            #permissions: permissions,
          },
        ),
        returnValue: _i3.Future<List<_i4.NotificationPermission>>.value(
            <_i4.NotificationPermission>[]),
      ) as _i3.Future<List<_i4.NotificationPermission>>);

  @override
  _i3.Future<void> showAlarmPage() => (super.noSuchMethod(
        Invocation.method(
          #showAlarmPage,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showGlobalDndOverridePage() => (super.noSuchMethod(
        Invocation.method(
          #showGlobalDndOverridePage,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showNotificationConfigPage({String? channelKey}) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotificationConfigPage,
          [],
          {#channelKey: channelKey},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getLocalization() => (super.noSuchMethod(
        Invocation.method(
          #getLocalization,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalization,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> setLocalization({required String? languageCode}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLocalization,
          [],
          {#languageCode: languageCode},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isNotificationActiveOnStatusBar({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isNotificationActiveOnStatusBar,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<int>> getAllActiveNotificationIdsOnStatusBar() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllActiveNotificationIdsOnStatusBar,
          [],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);
}
