// Mocks generated by Mockito 5.4.6 from annotations
// in audio_diaries_flutter/test/services/route_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:audio_diaries_flutter/screens/diary/domain/repository/answer_repository.dart'
    as _i4;
import 'package:audio_diaries_flutter/screens/diary/domain/repository/diary_repository.dart'
    as _i2;
import 'package:audio_diaries_flutter/screens/diary/domain/repository/prompt_repository.dart'
    as _i3;
import 'package:audio_diaries_flutter/screens/home/data/experiment.dart' as _i5;
import 'package:audio_diaries_flutter/screens/home/data/study.dart' as _i9;
import 'package:audio_diaries_flutter/screens/onboarding/data/questions.dart'
    as _i10;
import 'package:audio_diaries_flutter/screens/onboarding/domain/entities/questions_entity.dart'
    as _i11;
import 'package:audio_diaries_flutter/screens/onboarding/domain/repository/setup_repository.dart'
    as _i8;
import 'package:audio_diaries_flutter/services/preference_service.dart' as _i6;
import 'package:flutter/material.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDiaryRepository_0 extends _i1.SmartFake
    implements _i2.DiaryRepository {
  _FakeDiaryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromptRepository_1 extends _i1.SmartFake
    implements _i3.PromptRepository {
  _FakePromptRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnswerRepository_2 extends _i1.SmartFake
    implements _i4.AnswerRepository {
  _FakeAnswerRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExperimentModel_3 extends _i1.SmartFake
    implements _i5.ExperimentModel {
  _FakeExperimentModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferenceService extends _i1.Mock implements _i6.PreferenceService {
  MockPreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String?> getStringPreference({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStringPreference,
          [],
          {#key: key},
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> setStringPreference({
    required String? key,
    required String? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringPreference,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool?> getBoolPreference({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBoolPreference,
          [],
          {#key: key},
        ),
        returnValue: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);

  @override
  _i7.Future<bool> setBoolPreference({
    required String? key,
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBoolPreference,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int?> getIntPreference({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntPreference,
          [],
          {#key: key},
        ),
        returnValue: _i7.Future<int?>.value(),
      ) as _i7.Future<int?>);

  @override
  _i7.Future<bool> setIntPreference({
    required String? key,
    required int? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIntPreference,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<double?> getDoublePreference({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoublePreference,
          [],
          {#key: key},
        ),
        returnValue: _i7.Future<double?>.value(),
      ) as _i7.Future<double?>);

  @override
  _i7.Future<bool> setDoublePreference({
    required String? key,
    required double? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDoublePreference,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>?> getStringListPreference({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStringListPreference,
          [],
          {#key: key},
        ),
        returnValue: _i7.Future<List<String>?>.value(),
      ) as _i7.Future<List<String>?>);

  @override
  _i7.Future<bool> setStringListPreference({
    required String? key,
    required List<String>? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringListPreference,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> removePreference({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePreference,
          [],
          {#key: key},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> clearPreferences() => (super.noSuchMethod(
        Invocation.method(
          #clearPreferences,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [SetupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetupRepository extends _i1.Mock implements _i8.SetupRepository {
  MockSetupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DiaryRepository get diaryRepository => (super.noSuchMethod(
        Invocation.getter(#diaryRepository),
        returnValue: _FakeDiaryRepository_0(
          this,
          Invocation.getter(#diaryRepository),
        ),
      ) as _i2.DiaryRepository);

  @override
  _i3.PromptRepository get promptRepository => (super.noSuchMethod(
        Invocation.getter(#promptRepository),
        returnValue: _FakePromptRepository_1(
          this,
          Invocation.getter(#promptRepository),
        ),
      ) as _i3.PromptRepository);

  @override
  _i4.AnswerRepository get answerRepository => (super.noSuchMethod(
        Invocation.getter(#answerRepository),
        returnValue: _FakeAnswerRepository_2(
          this,
          Invocation.getter(#answerRepository),
        ),
      ) as _i4.AnswerRepository);

  @override
  void updateParticipant(String? name) => super.noSuchMethod(
        Invocation.method(
          #updateParticipant,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createProtocol() => super.noSuchMethod(
        Invocation.method(
          #createProtocol,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> getStudies({bool? partialCleanDB = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudies,
          [],
          {#partialCleanDB: partialCleanDB},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i5.ExperimentModel getExperiment() => (super.noSuchMethod(
        Invocation.method(
          #getExperiment,
          [],
        ),
        returnValue: _FakeExperimentModel_3(
          this,
          Invocation.method(
            #getExperiment,
            [],
          ),
        ),
      ) as _i5.ExperimentModel);

  @override
  dynamic setColorForStudy(List<_i9.StudyModel>? studies) =>
      super.noSuchMethod(Invocation.method(
        #setColorForStudy,
        [studies],
      ));

  @override
  void createNotifications({String? page}) => super.noSuchMethod(
        Invocation.method(
          #createNotifications,
          [],
          {#page: page},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<List<_i10.Questions>> getOnBoardingQuestions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnBoardingQuestions,
          [],
        ),
        returnValue: _i7.Future<List<_i10.Questions>>.value(<_i10.Questions>[]),
      ) as _i7.Future<List<_i10.Questions>>);

  @override
  _i7.Future<dynamic> saveOnBoardingQuestions(List<dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOnBoardingQuestions,
          [json],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  void saveOnBoardingAnswer(_i11.QuestionsEntity? question) =>
      super.noSuchMethod(
        Invocation.method(
          #saveOnBoardingAnswer,
          [question],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeAllQuestions() => super.noSuchMethod(
        Invocation.method(
          #removeAllQuestions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool?> uploadOnBoardingQuestions({bool? partialCleanDB = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadOnBoardingQuestions,
          [],
          {#partialCleanDB: partialCleanDB},
        ),
        returnValue: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);

  @override
  void clearStudies() => super.noSuchMethod(
        Invocation.method(
          #clearStudies,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> leaveStudy() => (super.noSuchMethod(
        Invocation.method(
          #leaveStudy,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i12.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPush,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didPop,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didRemove,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didReplace({
    _i12.Route<dynamic>? newRoute,
    _i12.Route<dynamic>? oldRoute,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #didReplace,
          [],
          {
            #newRoute: newRoute,
            #oldRoute: oldRoute,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTop(
    _i12.Route<dynamic>? topRoute,
    _i12.Route<dynamic>? previousTopRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeTop,
          [
            topRoute,
            previousTopRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStartUserGesture(
    _i12.Route<dynamic>? route,
    _i12.Route<dynamic>? previousRoute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #didStartUserGesture,
          [
            route,
            previousRoute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didStopUserGesture() => super.noSuchMethod(
        Invocation.method(
          #didStopUserGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
