# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Participants @model {
  STUDYCODE:ID!,
  PHYSICALLY_1:Int,
  PHYSICALLY_2:Int,
  PHYSICALLY_3:Int,
  PHYSICALLY_4:Int,
  PHYSICALLY_5:Int,
  PHYSICALLY_6:Int,
  EMOTIONALLY_1:Int,
  EMOTIONALLY_2:Int,
  EMOTIONALLY_3:Int,
  EMOTIONALLY_4:Int,
  EMOTIONALLY_5:Int,
  EMOTIONALLY_6:Int,
  INTENSITY_1:Int,
  INTENSITY_2:Int,
  INTENSITY_3:Int,
  INTENSITY_4:Int,
  INTENSITY_5:Int,
  INTENSITY_6:Int,
  LONELY_1:Int,
  LONELY_2:Int,
  LONELY_3:Int,
  LONELY_4:Int,
  LONELY_5:Int,
  LONELY_6:Int,
  LEFT_OUT_1:Int,
  LEFT_OUT_2:Int,
  LEFT_OUT_3:Int,
  LEFT_OUT_4:Int,
  LEFT_OUT_5:Int,
  LEFT_OUT_6:Int,
  SOCIAL_INTERACTION_1:Int,
  SOCIAL_INTERACTION_2:Int,
  SOCIAL_INTERACTION_3:Int,
  SOCIAL_INTERACTION_4:Int,
  SOCIAL_INTERACTION_5:Int,
  SOCIAL_INTERACTION_6:Int,
  UNDERSTOOD_1:Int,
  UNDERSTOOD_2:Int,
  UNDERSTOOD_3:Int,
  UNDERSTOOD_4:Int,
  UNDERSTOOD_5:Int,
  UNDERSTOOD_6:Int,
  STRESSED_1:Int,
  STRESSED_2:Int,
  STRESSED_3:Int,
  STRESSED_4:Int,
  STRESSED_5:Int,
  STRESSED_6:Int,
  WHERE_YOU_ARE_1:String,
  WHERE_YOU_ARE_2:String,
  WHERE_YOU_ARE_3:String,
  WHERE_YOU_ARE_4:String,
  WHERE_YOU_ARE_5:String,
  WHERE_YOU_ARE_6:String,
  PEOPLE_AROUND_YOU_1:String,
  PEOPLE_AROUND_YOU_2:String,
  PEOPLE_AROUND_YOU_3:String,
  PEOPLE_AROUND_YOU_4:String,
  PEOPLE_AROUND_YOU_5:String,
  PEOPLE_AROUND_YOU_6:String,
  DRINKS_1:Int,
  DRINKS_2:Int,
  DRINKS_3:Int,
  DRINKS_4:Int,
  DRINKS_5:Int,
  DRINKS_6:Int,
  STARTTIME:String
  ENDTIME:String
}