type UserMetadata @model @auth(rules: [{allow: public}]) {
  id: ID!
  participant: String
  start_study_date: String
  next_study_date: String
  recent_submit_date: String
  day1: String
  day2: String
  day3: String
  day4: String
  day5: String
  day6: String
}

type UserMetadataDev @model @auth(rules: [{allow: public}]) {
  id: ID!
  start_study_date: String
  next_study_date: String
  recent_submit_date: String
  day1: String
  day2: String
  day3: String
  day4: String
  day5: String
  day6: String
}

type Participants @model @auth(rules: [{allow: public}]) {
  studycode: ID!
  physically_1: Int
  physically_2: Int
  physically_3: Int
  physically_4: Int
  physically_5: Int
  physically_6: Int
  emotionally_1: Int
  emotionally_2: Int
  emotionally_3: Int
  emotionally_4: Int
  emotionally_5: Int
  emotionally_6: Int
  intensity_1: Int
  intensity_2: Int
  intensity_3: Int
  intensity_4: Int
  intensity_5: Int
  intensity_6: Int
  lonely_1: Int
  lonely_2: Int
  lonely_3: Int
  lonely_4: Int
  lonely_5: Int
  lonely_6: Int
  left_out_1: Int
  left_out_2: Int
  left_out_3: Int
  left_out_4: Int
  left_out_5: Int
  left_out_6: Int
  social_interaction_1: Int
  social_interaction_2: Int
  social_interaction_3: Int
  social_interaction_4: Int
  social_interaction_5: Int
  social_interaction_6: Int
  understood_1: Int
  understood_2: Int
  understood_3: Int
  understood_4: Int
  understood_5: Int
  understood_6: Int
  stressed_1: Int
  stressed_2: Int
  stressed_3: Int
  stressed_4: Int
  stressed_5: Int
  stressed_6: Int
  where_you_are_1: String
  where_you_are_2: String
  where_you_are_3: String
  where_you_are_4: String
  where_you_are_5: String
  where_you_are_6: String
  people_around_you_1: String
  people_around_you_2: String
  people_around_you_3: String
  people_around_you_4: String
  people_around_you_5: String
  people_around_you_6: String
  starttime_1: String
  starttime_2: String
  starttime_3: String
  starttime_4: String
  starttime_5: String
  starttime_6: String
  endtime_1: String
  endtime_2: String
  endtime_3: String
  endtime_4: String
  endtime_5: String
  endtime_6: String
} 






type ParticipantsNew @model @auth(rules: [{allow: public}]) {
  studycode: String!
  physically_1: Int
  physically_2: Int
  physically_3: Int
  physically_4: Int
  physically_5: Int
  physically_6: Int
  emotionally_1: Int
  emotionally_2: Int
  emotionally_3: Int
  emotionally_4: Int
  emotionally_5: Int
  emotionally_6: Int
  intensity_1: Int
  intensity_2: Int
  intensity_3: Int
  intensity_4: Int
  intensity_5: Int
  intensity_6: Int
  lonely_1: Int
  lonely_2: Int
  lonely_3: Int
  lonely_4: Int
  lonely_5: Int
  lonely_6: Int
  left_out_1: Int
  left_out_2: Int
  left_out_3: Int
  left_out_4: Int
  left_out_5: Int
  left_out_6: Int
  social_interaction_1: Int
  social_interaction_2: Int
  social_interaction_3: Int
  social_interaction_4: Int
  social_interaction_5: Int
  social_interaction_6: Int
  understood_1: Int
  understood_2: Int
  understood_3: Int
  understood_4: Int
  understood_5: Int
  understood_6: Int
  stressed_1: Int
  stressed_2: Int
  stressed_3: Int
  stressed_4: Int
  stressed_5: Int
  stressed_6: Int
  where_you_are_1: String
  where_you_are_2: String
  where_you_are_3: String
  where_you_are_4: String
  where_you_are_5: String
  where_you_are_6: String
  people_around_you_1: String
  people_around_you_2: String
  people_around_you_3: String
  people_around_you_4: String
  people_around_you_5: String
  people_around_you_6: String
  starttime_1: String
  starttime_2: String
  starttime_3: String
  starttime_4: String
  starttime_5: String
  starttime_6: String
  endtime_1: String
  endtime_2: String
  endtime_3: String
  endtime_4: String
  endtime_5: String
  endtime_6: String
} 


type ParticipantsDev  @model @auth(rules: [{allow: public}]) {
  id: ID!
  physically_1: Int
  physically_2: Int
  physically_3: Int
  physically_4: Int
  physically_5: Int
  physically_6: Int
  emotionally_1: Int
  emotionally_2: Int
  emotionally_3: Int
  emotionally_4: Int
  emotionally_5: Int
  emotionally_6: Int
  intensity_1: Int
  intensity_2: Int
  intensity_3: Int
  intensity_4: Int
  intensity_5: Int
  intensity_6: Int
  lonely_1: Int
  lonely_2: Int
  lonely_3: Int
  lonely_4: Int
  lonely_5: Int
  lonely_6: Int
  left_out_1: Int
  left_out_2: Int
  left_out_3: Int
  left_out_4: Int
  left_out_5: Int
  left_out_6: Int
  social_interaction_1: Int
  social_interaction_2: Int
  social_interaction_3: Int
  social_interaction_4: Int
  social_interaction_5: Int
  social_interaction_6: Int
  understood_1: Int
  understood_2: Int
  understood_3: Int
  understood_4: Int
  understood_5: Int
  understood_6: Int
  stressed_1: Int
  stressed_2: Int
  stressed_3: Int
  stressed_4: Int
  stressed_5: Int
  stressed_6: Int
  where_you_are_1: String
  where_you_are_2: String
  where_you_are_3: String
  where_you_are_4: String
  where_you_are_5: String
  where_you_are_6: String
  people_around_you_1: String
  people_around_you_2: String
  people_around_you_3: String
  people_around_you_4: String
  people_around_you_5: String
  people_around_you_6: String
  starttime_1: String
  starttime_2: String
  starttime_3: String
  starttime_4: String
  starttime_5: String
  starttime_6: String
  endtime_1: String
  endtime_2: String
  endtime_3: String
  endtime_4: String
  endtime_5: String
  endtime_6: String
} 