name: Main workflow

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install dependencies
        run: flutter pub get

      - name: Create DUMMY KEYS.dart for CI
        run: |
          mkdir -p lib/core/secrets
          echo "// Dummy API keys for CI" > lib/core/secrets/keys.dart
          echo "const apiKey = 'dummy';" >> lib/core/secrets/keys.dart
          echo "const pendoKey = 'dummy';" >> lib/core/secrets/keys.dart

      - name: install the database
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test test/
        timeout-minutes: 10

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6"
          bundler-cache: true
          working-directory: android

      - name: Deploy Android app to Firebase via Fastlane
        working-directory: android
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          bundle exec fastlane deploy_to_firebase
